@startuml 

title Заказ

|Покупатель|
start

:Покупка заказа;

|Сервис заказа|
:Валидация заказа;
:Изменить количество товаров в магазине;
:Изменение статуса заказа;

fork 
|Покупатель|
:Получение чека;
stop

fork again 
|Сервис доставки|
:Заказ добавлен в список;

end fork


@enduml