@startuml ИС доставки товаров из магазина

Title: Диаграмма коммуникации интернет магазина

actor Клиент
actor ИнтернетМагазин
actor Курьер

Клиент -> ИнтернетМагазин : Оформление заказа
ИнтернетМагазин -> Клиент : Отправка чека
ИнтернетМагазин -> Курьер : Добавление в спосок заказов
Курьер -> ИнтернетМагазин : Подтверждение выбора или назначения на заказ
ИнтернетМагазин -> Клиент : Оповещение о доставке
Курьер -> Клиент : Доставка товара
Курьер -> ИнтернетМагазин : Уведомление о конце доставки

@enduml
