@startuml

component "Клиент"

package "Сервер" {
    component "Сервис заказов"
    component "Сервис оплаты"
    component "Сервис доставки"
    component "Сервис уведомлений"
}

[Клиент] --> [Сервис заказов]
[Сервис заказов] --> [Сервис оплаты]
[Сервис заказов] --> [Сервис уведомлений]
[Сервис уведомлений] --> [Клиент]
[Сервис заказов] --> [Сервис доставки]

@enduml