@startuml

title Диаграмма состояний для приобретения товара в интернет магазине

[*] --> ГлавнаяCтраница

ГлавнаяCтраница --> ОформлениеPаказа : "Оформить заказ"

ОформлениеPаказа --> Доставка : "Выбор способа доставки"
ОформлениеPаказа --> Корзина : "Добавление товара в корзину"
ОформлениеPаказа --> ОформлениеPаказа : "Удаление товара из корзины"
ОформлениеPаказа --> ОформлениеPаказа : "Изменение количества товара в корзине"
ОформлениеPаказа --> Оплата : "Переход к оплате"

Доставка --> ОформлениеPаказа : "Назад"
Доставка --> Оплата : "Далее"

Оплата --> ОформлениеPаказа : "Назад"
Оплата --> УспешныйЗаказ : "Оплата прошла успешно"

Корзина --> ОформлениеPаказа : "Перейти к оформлению"
Корзина --> Корзина : "Изменение количества товара"
Корзина --> ГлавнаяCтраница : "Продолжить покупки"

УспешныйЗаказ --> ГлавнаяCтраница : "Продолжить покупки"

ГлавнаяCтраница --> [*]

@enduml