
@startuml ИС доставки товаров из магазина

class User {
    + Long id
    + String first_name
    + String last_name
    + String patronymic
    + String email
    + String phone
}

class Category {
    + Long id
    String name
}

class Customer {
    + Address defaultAddress
    + PurshaseMethod preferredMethod
}

class Basket {
    + Long id
    + Long user_id
    + Long[] basket_items
}

class BasketItem {
    + Long id
    + User user_id
    + Long product_id
    + int number
}

enum Status {
    В пути
    Готовится к отправке
    Отклонено
    Доставлено
    Отказ
}

class Order {
    + Long id
    + PurshaseMethod purchase_method
    + BasketItem products
    + Status status
    + OrderMethod order_method
    + DeliveryCompany company
    + Address address
}

class BaseProduct {
    + Long id
    + String name
    + Category category
}

class Deliveryman {
    + Long id
    + String first_name
    + String second_name
    + String patronymic
    + String phone
    + String  email 
    + String  password
}

enum PurshaseMethod {
    Наличкой
    Карточкой
}

' tight binding
Basket *-- BasketItem
Order o-- Deliveryman
BaseProduct o-- Category


User <|-- Customer
BasketItem *-- Order


@enduml
