@startuml
title Последовательность приобретения товара в интернет-магазине

actor Покупатель
actor РаботникМагазина
actor Курьер


activate Покупатель
Покупатель -> Покупатель : получение чека
activate РаботникМагазина

РаботникМагазина -> Курьер : Сбор заказа и передача заказа курьеру
deactivate РаботникМагазина
activate Курьер
Курьер --> Покупатель : доставка товара
Курьер --> Курьер : при отказе, обратная доставка
deactivate Курьер

@enduml
