@startuml

' Информационная система «Интернет-магазин», торгующий:
' ­Продуктами с доставкой заказчику

' 1 магазин-склад который продаёт продукты сам и осуществляет доставку с помощью курьеров
' Нужно вести подсчёт товаров
' Нужно хранить заявки на доставку
' Нужно отслеживать статус заказа
' В случае доставки на дальнюю дистанцию - используются услуги компании грузоперевозчика (Почта, СДЭК или другие)

' Кто заходит на сайт и может стать Покупателем.
:Пользователь: as User 
' Кто хочет купить что-то или уже купил через сайт
:Покупатель: as Customer
' Кто предоставляет список товаров Покупателю. Ведёт подсчёт товаров и актуализирует данные по товарам на складе (Изменение количества после успещного заказа или при получении новой партии)
:Работник: as Worker
' Кто доставляет заказ к Покупателю  
:Курьер: as Courier


( Информация о товаре ) as ProductInfo
ProductInfo --> ( Описание )
ProductInfo --> ( Количество )
ProductInfo --> ( Цена )

Worker ->  ProductInfo
Worker -->  ( Поддержание актуальности данных )

'-----------------------
( Товар ) as Product
Product --> ( Поиск, Просмотр )
Product --> ( Доступен ли для покупки )

User --> Product
User --> ( Регистрация, Вход )
' User --> ( Выбор региона )

Customer -|> User

'-----------------------
( Товар в корзине ) as BasketItem
( Оформление заказа ) as MakingOrder
( Получение заказа ) as ReceivingOrder
BasketItem -> ( Добавление, удаление )
BasketItem --> ( Пометить активным или неактивным )
BasketItem --> ( Выбор количества товара в корзине )
MakingOrder --> ( Выбор способа доставки или самовывоз )
MakingOrder --> ( Выбор адреса доставки )
MakingOrder  --> ( Оформить заказ )
MakingOrder --> ( Получить чек )
ReceivingOrder --> ( Оповещение, что товар доставлен )
ReceivingOrder --> ( Отказаться от товара )

Customer -> BasketItem
Customer  -right-> MakingOrder
Customer --> ReceivingOrder

'-----------------------
( Заказ ) as order
order -> ( Выбор )
order --> ( Посмотреть детали )
' В дороге, Доставлено, Возврат
order --> ( Изменить статус доставки )

Courier -> order
Courier --> ( Посмотреть список заказов )


@enduml